[package]
name = "sr"
version = "0.1.0"
edition = "2021"

[dependencies]
base = { path = "base" }
data = { path = "data" }
excel = { path = "excel" }

[workspace]
members = [
  "base",
  "data",
  "excel",
  "model",
  "format",
]
