[package]
name = "format"
version = "0.1.0"
edition = "2021"

[dependencies]
terminal_size = { version = "0.4" }
thousands = { version = "0.2" }

base = { path = "../base" }
data = { path = "../data" }
model = { path = "../model" }
