[package]
name = "base"
version = "0.1.0"
edition = "2021"

[dependencies]
either = { version = "1" }
fnv = { version = "1" }
indexmap = { version = "2", features = ["serde"] }
multimap = { version = "0.10" }
